dist: trusty
sudo: required

os:
  - linux

git:
  depth: 1

addons:
  apt:
    packages:
      - socat

language: d
d:
  # actual
  - dmd-2.088.1
  - ldc-1.18.0
  # newer
  - dmd-nightly
  - ldc-beta
  # used
  - dmd-2.087.1
  - ldc-1.17.0
  # old
  - dmd-2.078.3
  - ldc-1.8.0
  # other
  - dmd-2.082.1
  - dmd-2.081.1
  - ldc-1.11.0
  - dmd-2.080.1
  - dmd-2.079.1
  - ldc-1.10.0
  - ldc-1.9.0

matrix:
  allow_failures:
    - d: dmd-nightly
      os: linux
    - d: ldc-beta
      os: linux

script: 
  - dub test --compiler=${DC} --build=unittest-cov

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && ${DC} == "dmd" ]]; then bash <(curl -s https://codecov.io/bash); fi